package com.example.android.unscramble.ui.game

const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

val allWordsList: List<String> =
    listOf("hewan",
        "mobil",
        "anekdot",
        "alfabet",
        "semua",
        "luar biasa",
        "muncul",
        "balon",
        "keranjang",
        "bangku",
        "terbaik",
        "ulang tahun",
        "buku",
        "tas kerja",
        "kamera",
        "berkemah",
        "lilin",
        "kucing",
        "kembang kol",
        "obrolan",
        "anak-anak",
        "kelas",
        "klasik",
        "ruang kelas",
        "kopi",
        "berwarna-warni",
        "kue",
        "kreatif",
        "pelayaran",
        "menari",
        "siang hari",
        "dinosaurus",
        "kenop pintu",
        "makan",
        "mimpi",
        "senja",
        "makan",
        "gajah",
        "zamrud",
        "menyeramkan",
        "listrik",
        "selesai",
        "bunga",
        "mengikuti",
        "rubah",
        "bingkai",
        "gratis",
        "sering",
        "corong",
        "hijau",
        "gitar",
        "belanjaan",
        "kaca",
        "hebat",
        "tertawa kecil",
        "potong rambut",
        "setengah",
        "buatan sendiri",
        "terjadi",
        "madu",
        "buru-buru",
        "seratus",
        "es",
        "iglo",
        "berinvestasi",
        "mengundang",
        "ikon",
        "memperkenalkan",
        "lelucon",
        "ceria",
        "jurnal",
        "melompat",
        "bergabung",
        "kanguru",
        "papan ketik",
        "dapur",
        "koala",
        "baik hati",
        "kaleidoskop",
        "pemandangan",
        "terlambat",
        "tertawa",
        "belajar",
        "lemon",
        "surat",
        "bunga lili",
        "majalah",
        "laut",
        "marshmallow",
        "labirin",
        "meditasi",
        "melodi",
        "menit",
        "monumen",
        "bulan",
        "sepeda motor",
        "gunung",
        "musik",
        "utara",
        "hidung",
        "malam",
        "nama",
        "tidak pernah",
        "bernegosiasi",
        "nomor",
        "berlawanan",
        "gurita",
        "pohon ek",
        "pesanan",
        "buka",
        "kutub",
        "kemas",
        "lukisan",
        "orang",
        "piknik",
        "bantal",
        "pizza",
        "podcast",
        "presentasi",
        "anak anjing",
        "teka-teki",
        "resep",
        "rilis",
        "restoran",
        "berputar",
        "memutar kembali",
        "ruangan",
        "berlari",
        "rahasia",
        "biji",
        "kapal",
        "kemeja",
        "harus",
        "kecil",
        "pesawat luar angkasa",
        "mengamati bintang",
        "keterampilan",
        "jalan",
        "gaya",
        "matahari terbit",
        "taksi",
        "rapi",
        "pengatur waktu",
        "bersama",
        "gigi",
        "turis",
        "perjalanan",
        "truk",
        "di bawah",
        "berguna",
        "unicorn",
        "unik",
        "mengangkat",
        "seragam",
        "vas",
        "biola",
        "pengunjung",
        "visi",
        "volume",
        "pemandangan",
        "anjing laut",
        "berkelana",
        "dunia",
        "musim dingin",
        "sumur",
        "angin puyuh",
        "sinar-X",
        "xilofon",
        "yoga",
        "yogurt",
        "yoyo",
        "kamu",
        "tahun",
        "lezat",
        "zebra",
        "zigzag",
        "zoologi",
        "zona",
        "semangat",
        "qohary",
        "love",
        "adnaw")